
spring:
    datasource:
        mongodb:
            host: localhost
            port: 27017
            database: test


server:
    port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        

